version: '2'

volumes:
    logs:
        driver: local

services:
    slim:
        build:
          dockerfile: ./Dockerfile
          context: .
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public index.php
        environment:
            db: "mongodb://mongodb:27020"
        ports:
            - 8081:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs
        depends_on:
          - mongodb
    mongodb:
        image: mongo:3.6
        container_name: mongo
        restart: always
        volumes:
            - ./data/db/mongo:/data/db
        ports:
            - "27020:27017"
        command: --storageEngine wiredTiger
