version: '3'

volumes:
    logs:
        driver: local

services:
    geoip_php:
        build:
          dockerfile: ./Dockerfile
          context: .
        image: geoip_slim:latest
        container_name: geoip_php
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public index.php
        environment:
            db: pgsql:host=postgres;user=postgres;password=mysecretpassword;port=5432
            tableName: geo_ip
        ports:
            - 8081:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs
        depends_on:
          - postgres
    postgres:
        image: postgres:10
        container_name: postgres
        restart: always
        ports:
            - "5432:5432"
